### ISSUE TITLE
Add relationships to slimmer

### ISSUE THREAD

**Issue by jannahastings** [enanomapper/slimmer#13]
Currently the slimmer only accepts and "slims" classes. We need to add relationships, which can also be duplicated in much the same fashion as classes are.

**Comment by egonw** [comment]
@jannahastings can you please give it a spin and see if it works for you? It uses the exact same syntax. Since one IRI is either a class or a property, it just tries uses the same stack of IRIs as input for the slimming and runs this against both entities...

**Comment by egonw** [comment]
Patch was not working well, causing bug #14.
