### ISSUE TITLE
problems with relationship slimming?

### ISSUE THREAD

**Issue by jannahastings** [enanomapper/slimmer#14]
Testing adding relationship IRIs for BAO, although the build shows as successful the result is strange (no labels, relationships are still there) and there is an error report in the workspace. 

Error report: https://jenm.bigcat.maastrichtuniversity.nl/job/BAO/ws/hs_err_pid2187.log/*view*/

**Comment by egonw** [comment]
BTW, that Java core dump is unrelated. That happens sometimes...

**Comment by egonw** [comment]
The unit tests suggest it is doing what I want it to do, but have to make sure that on Jenkins it is also removing all properties except those listed in the .props file...

**Comment by egonw** [comment]
I believe I may have tackled it finally...

![image](https://cloud.githubusercontent.com/assets/26721/11447615/3d98f4d8-9549-11e5-88b1-4d429544bb61.png)

As you can see, the development release has only 2 data|object properties...
