### ISSUE TITLE
Random extra class in obi slim file

### ISSUE THREAD

**Issue by jannahastings** [enanomapper/slimmer#17]
The OBI slim file includes the class BFO_0000003 (without metadata) which is not included in the instructions. The only place that the class is used in the slim file is in the range of the preceded_by and precedes relations. As this class is not included in the instructions I would not expect it to be included in the resulting slim file.

**Comment by egonw** [comment]
This depends on getting the properties to be slimmed properly... see issue #13

**Comment by egonw** [comment]
Fixed.
