### ISSUE TITLE
Problems with PATO and CHEMINF slims

### ISSUE THREAD

**Issue by jannahastings** [enanomapper/slimmer#19]
There seems to be something odd going on with the slimmer. 

In CHEMINF, despite clearly specifying the same parent class for 'molecular entity quality', 'chemical substance quality' and 'surface area' which I newly added to the cheminf.iris for export, only one of the three is getting the correct parent allocated, while the other two are assigned no parent class. 

In PATO, newly assigned classes for export, e.g. size, are not being included in the resulting slim file, despite the build executing on commit as usual.

**Comment by egonw** [comment]
Mmm... I see this in the log file:

    Adding super class axiom: SubClassOf(<http://semanticscience.org/resource/CHEMINF_000031> <http://purl.obolibrary.org/obo/BFO_0000019>)

**Comment by egonw** [comment]
OK, I finally isolated the issue... it's deleting the BFO super class, only just before the adding the new subClassOf axiom of the one that does get kept...  *sigh* :/

**Comment by egonw** [comment]
Confirmed fixed on Jenkins:

        <owl:Class rdf:about="http://semanticscience.org/resource/CHEMINF_000031">
            <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/BFO_0000019"/>
            <obo:IAO_0000115>A molecular entity quality is a quality which inheres in a molecular entity.</obo:IAO_0000115>
            <dc:description>A molecular entity quality is a quality which inheres in a molecular entity.</dc:description>
            <rdfs:label>molecular entity quality</rdfs:label>
        </owl:Class>

**Comment by egonw** [comment]
The PATO class is confirmed to be in the slimmed file too:

    

        <owl:Class rdf:about="http://purl.obolibrary.org/obo/PATO_0000117">
            <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/BFO_0000019"/>
            <obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A morphology quality inhering in a bearer by virtue of the bearer&apos;s physical magnitude.</obo:IAO_0000115>
