### ISSUE TITLE
ccont.owl download times out

### ISSUE THREAD

**Issue by egonw** [enanomapper/slimmer#21]
Janna, are there alternative download locations? Jenkins reports:

    --2015-09-08 06:43:09--  (try:11)  http://livercancer.imbi.uni-heidelberg.de/ccont.owl
    Connecting to livercancer.imbi.uni-heidelberg.de (livercancer.imbi.uni
        -heidelberg.de)|129.206.228.156|:80... failed: Connection timed out.
    Retrying.

**Comment by JKChang2015** [comment]
now fixed
