### ISSUE TITLE
Problem with headclass "Toxicity" within "Information Content Entity"

### ISSUE THREAD

**Issue by lrieswijk** [enanomapper/slimmer#40]
There seems to be a change in the subclasses present in the headclass of "toxicity" which is now under the superclass of "information content entity". Before this was under "disposition" so something must have changed in composing the eNM ontology. NOTE: under the toxicity class there are some classes which have manually been added to the eNM ontology.

**Comment by egonw** [comment]
OK, to me this is like this: there is a disposition that something is toxic, but what we practically mostly deal with is measured data that tells us that something gave a positive effect for some toxicity endpoint. What now is under ICE, is the latter. Thus, I think it should remain there, and that the figure in the paper is talking about the disposition of toxicity instead.
