### ISSUE TITLE
Why was "skin sensitization" and "skin irritation" directly under "toxicological endpoint" and not "dermal toxicity"?

### ISSUE THREAD

**Issue by lrieswijk** [enanomapper/slimmer#41]
Why were the terms "skin sensitization" and "skin irritation" not put under "dermal toxicity" but made a separate class. These terms were manually added to the eNM ontology so please can you explain why this decision was made @jannahastings ?

**Comment by vedina** [comment]
Probably because in the ECHA endpoint classification & OECD guidance (and the derived OpenTox ontology used as source for these manually added terms) these are directly under "Toxicity" .

**Comment by egonw** [comment]
@vedina, in your opinion, is it important to keep it directly under there, or is somewhere as subclass fine too?

**Comment by vedina** [comment]
Subclass could be fine.

**Comment by JKChang2015** [comment]
https://github.com/enanomapper/ontologies/commit/56d4be6300d218832ca527ecec7d93c60b9f9c92

done
