### ISSUE TITLE
Update library owlapi-distribution to latest version

### ISSUE THREAD

**Issue by nunogit** [enanomapper/slimmer#46]
Update pom.xml to have the latest version of owlapi-distribution

	<dependency>
    		<groupId>net.sourceforge.owlapi</groupId>
    		<artifactId>owlapi-distribution</artifactId>
    		<version>4.3.2</version>
    	</dependency>

I did a copy and updated to version 5.1.11 but had issues compiling. Changes at the java code might be required.

Ref.:
https://mvnrepository.com/artifact/net.sourceforge.owlapi/owlapi-distribution

**Comment by egonw** [comment]
Can you plz copy/paste the compile errors here too?

**Comment by egonw** [comment]
Fixed in https://github.com/enanomapper/slimmer/commit/6cbf30c6344b9f4cea747a1b97827f2f5d627abd
