### ISSUE TITLE
Possible bug with assigning parent in cheminf-slim?

### ISSUE THREAD

**Issue by jannahastings** [enanomapper/slimmer#9]
There might be a bug with how the parent class (specified in ()) is assigned in the case of cheminf. For cheminf I included only one class with descendents -- chemical descriptor -- and assigned it the parent IAO_0000030 i.e. information content entity. However, in the resulting SLIM the class has no specified parent. I suspect this is because the IAO class that I want to delegate as parent IS actually present in the source version of cheminf, so it gets removed along with the rest of the imported IAO. However, despite the fact that it is present in cheminf I don't want to import it from there as we are importing direct from IAO.

**Comment by egonw** [comment]
This was the same problem as issue #19. I confirmed the fix on Jenkins:

        
    
        <owl:Class rdf:about="http://semanticscience.org/resource/CHEMINF_000123">
            <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/IAO_0000030"/>
